### ISSUE TITLE
Please provide details on ideal system attributes

### ISSUE THREAD

**Issue by shivampotdar** [evanseitz/cryoEM_synthetic_continua#1]
I have been trying to run the files in this repository, but there are number of dependency issues. First of all, many of the packages mentioned in the text file are no longer present on conda repositories. I tried to fix that by getting newer versions, but still there is no clarity on what versions of Chimera, Pymol, Phenix are to be used.

**Comment by evanseitz** [comment]
Hi @shivampotdar , the three packages you've listed are all standards in structural biology pipelines (you'll eventually also need RELION and EMAN); each of these are usually installed standalone to the python environment (with installation instructions on their homepage). I believe all versions have the basic modules available that I'm using here, but here's my exact info:

**Phenix:** Version 1.17rc5-3630
**EMAN** 2.31 final
**PyMOL:** 2.3.3
**Chimera:** 1.13
**RELION:** 3.0.8 Precision: BASE=double, CUDA-ACC=single

Before running the scripts where these commands are called, you'll need to source each one (depending on the script).

I'll make sure to add this in the readme, thank you for addressing this.

**Comment by evanseitz** [comment]
Hi @shivampotdar - I've updated the readme with further details. Please let me know if you have any other questions.

**Comment by shivampotdar** [comment]
Thank you for your quick response @evanseitz . I've fixed some of the dependency issues manually and have reached till the 4_GenMRC stage. But for the next one, I'm facing PyQt related issues. Upgrading icu or pyicu ultimately results in many conflicts and fails. Do you have any suggestions on how shall I go about that?
Thanks

**Comment by evanseitz** [comment]
@shivampotdar are you using the isolated anaconda environment `env_{your_os}_64.txt` in the main directory of the repo? You'll have to source it each time before you run one of the python scripts (with syntax shown in the readme).

**Comment by shivampotdar** [comment]
Yes I'm using that. I think it is due to OS version upgrade, I am on Ubuntu 20.04 now.
Nonetheless, I worked around this by using my system python (by pip installing numpy matplotlib pylab scipy mrcfile)

**Comment by evanseitz** [comment]
Okay, this might be challenging to pinpoint. Just as a note, the conda environment `synth` in the repo is highly particular... if you tried to install anything additional (via pip, conda, brew, etc) while `synth` was active (sourced), it could have created a conflict. If so, you would have to delete the env and recreate it.

**Comment by shivampotdar** [comment]
Yes I think I installed a module or two. Nonetheless, my work around helped and I am able to run all the scripts. Thanks a lot for your help @evanseitz
I'll mark this issue as closed.
